### ISSUE TITLE
Add fill: currentColor to svg

### ISSUE THREAD

**Issue by tadatuta** [tadatuta/bem-font-awesome-icons#2]
```css
.icon svg {
    fill: currentColor;
}
```

It will give possibility to set color via `icon` block.

See http://jsfiddle.net/qfox/e7j8mcLv/ as example.
